version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jyankenpon"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15tdtub9cd9ua"
s3_prefix = "jyankenpon"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=230803652915.dkr.ecr.ap-northeast-1.amazonaws.com/jyankenponecb9f65c/helloworldfunction19d43fc4repo"]
