version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::230803652915:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-XK1BA53UY526"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::230803652915:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-12WD1AK9X86E1"
cloudformation_execution_role = "arn:aws:iam::230803652915:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1UTJ2S0K73PAY"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1ai0akfi5zaea"
image_repository = "230803652915.dkr.ecr.ap-northeast-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-1x7ysznsmxai"
region = "ap-northeast-1"

[stage]
[stage.pipeline_bootstrap]
[stage.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::230803652915:role/aws-sam-cli-managed-stage-pi-PipelineExecutionRole-1K9IOAKBQ30MM"
cloudformation_execution_role = "arn:aws:iam::230803652915:role/aws-sam-cli-managed-stage-CloudFormationExecutionR-1XI6YXMEYRBL5"
artifacts_bucket = "aws-sam-cli-managed-stage-pipelin-artifactsbucket-rh0ihakwowh4"
image_repository = "230803652915.dkr.ecr.ap-northeast-1.amazonaws.com/aws-sam-cli-managed-stage-pipeline-resources-imagerepository-wytf59brkkjd"
region = "ap-northeast-1"
